name: Lambda Deploy
on:
  push:
    branches:
      - lambda-deploy
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Zip (connect-py)
        run: cd ./src/connect-py && zip connect-py.zip lambda_function.py
      - name: Deploy Lambda (connect-py)
        run: aws lambda update-function-code 
          --function-name connect 
          --zip-file fileb://connect-py.zip
